# default false
release_mode = false
# default DEBUG, DEBUG INFO WARN ERROR OFF
log_level = "DEBUG"

[app]
name = "kamgo"
version = "0.0.1"

[server]
graceful = true
addr = ":9093"

[kam_database]
name = "kamailio"
user_name = "kamailio"
pwd  = "Tiger1234"
host = "127.0.0.1"
port = "3306"
